INSERT INTO course(COURSE_NAME, STATE_ACTIVE ) VALUES('DISEÑO Y CONSTRUCCION DE SOFTWARE','true');
INSERT INTO course(COURSE_NAME, STATE_ACTIVE ) VALUES('ARQUITECTURA DE SOFTWARE','true');
INSERT INTO course(COURSE_NAME, STATE_ACTIVE ) VALUES('SEMINARIO DE LA REALIDAD PERUANA','true');
INSERT INTO course(COURSE_NAME, STATE_ACTIVE ) VALUES('UN TIPICO CURSO DE LA UPC','true');
INSERT INTO course(COURSE_NAME, STATE_ACTIVE ) VALUES('DISEÑO Y CONSTRUCCION DE SOFTWARE','true');
INSERT INTO course(COURSE_NAME, STATE_ACTIVE ) VALUES('BIGDATA','true');



